# Generated by Django 4.0 on 2022-12-21 22:01

import django.core.validators
from django.db import migrations, models
import learndjango.urlpatterns.models


class Migration(migrations.Migration):

    replaces = [('urlpatterns', '0001_initial'), ('urlpatterns', '0002_test_model_city'), ('urlpatterns', '0003_alter_test_model_address_alter_test_model_name')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test_Model',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False, validators=[learndjango.urlpatterns.models.name_min_length])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(5)])),
                ('city', models.CharField(default='CA', max_length=2)),
            ],
        ),
    ]
