# Generated by Django 4.0 on 2022-12-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlpatterns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_model',
            name='city',
            field=models.CharField(default='CA', max_length=2),
        ),
    ]
