# Generated by Django 4.0 on 2022-12-21 21:31

import django.core.validators
from django.db import migrations, models
import learndjango.urlpatterns.models


class Migration(migrations.Migration):

    dependencies = [
        ('urlpatterns', '0002_test_model_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_model',
            name='address',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='test_model',
            name='name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, validators=[learndjango.urlpatterns.models.name_min_length]),
        ),
    ]
